### ISSUE TITLE
Stylus / CSS

### ISSUE THREAD

**Issue by jonathanhudak** [shiftsave/anni-platform#1]
https://github.com/hudakdidit/my-boilerplate

Here's my boilerplate to demo stylus, autoprefixer, etc with webpack.

**Comment by shiftsave** [comment]
@hudakdidit awesome! I'm going to try to implement tonight.

**Comment by shiftsave** [comment]
@hudakdidit How fast do you think you could help me setup stylus and/or css modules? I implemented some basic styling for now, so no rush but would be nice to start styling in the next couple weeks!
