### ISSUE TITLE
Setup Stylus with local scope

### ISSUE THREAD

**Issue by shiftsave** [shiftsave/anni-platform#11]
I tried doing it in the same way as Sass but couldn't get it to work.

**Comment by jonathanhudak** [comment]
Could you explain more what you mean?

**Comment by shiftsave** [comment]
@hudakdidit  I want a o implement local ident name like I did on my other React app with Sass

``      {
        test: /\.scss$/,
        loaders: ["style", "css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]", "sass"]
      }``

The localIdentName so that when styl files are imported per file are scopes with a hash. That said, I don't think this is pressing at all given the amount of styles we will have for this first version and nesting styles with class names has worked really well. 

I've been nesting as such

``.componentClassName``
    ``.className``

Abs haven't hit any issues thus far because the nested class name is targeted directly given that the parent class is always unique gven it's the name of the component.
