### ISSUE TITLE
Implement Orderable List Component

### ISSUE THREAD

**Issue by shiftsave** [shiftsave/anni-platform#35]
The Orderable List Component should be able to take an array of objects and allow them to be re-ordered and maintain order in the store.

#### Project Details Structure example
```javascript
items = [
  { 
    name: Introduction // Editable via <TextArea /> component
    content: {< Headline />}
    orderIndex: 1
    projectId: 1
  },
  { 
    name: Text Editor // Editable via <TextArea /> component
    content: {< TextEditor />}
    orderIndex: 1
    projectId: 2
  },
  { 
    name: Moodboard // Editable via <TextArea /> component,
    content: {<ImageList />},
    orderIndex: 1,
    projectId:3
  }
]
```

#### Image List object example
```javascript
items = [
  { 
    content: {< Image />}
    orderIndex: 1
    projectId: 1
  },
  { 
    content: {< Image />}
    orderIndex: 1
    projectId: 2
  },
  { 
    content: {<Image />},
    orderIndex: 1,
    projectId:3
  }
]
```

**Comment by shiftsave** [comment]
@hudakdidit started thinking about the orderable list component and how this can be reused in almost all instances of the app, from image lists to actual project structure.

I noted my thoughts here on how this could be flexible enough for at least these two major use types, feel free to add/remove to the issue.

**Comment by jonathanhudak** [comment]
@shiftsave hey I don't think we'll need to make an orderable list component, the react-sortable-hoc essentially already provides one. I can work it into your imageList PR if that's cool?

**Comment by shiftsave** [comment]
Oh ok cool, that'll be awesome! I've been doing some work today I'll update the project tonight. With some screens

**Comment by shiftsave** [comment]
@hudakdidit that library is 👌🏽
