### ISSUE TITLE
Create the image gallery component for Styleframes view

### ISSUE THREAD

**Issue by shiftsave** [shiftsave/anni-platform#48]
This view requires the ability to use the FileUploader to upload images to the collection and allow the user to view, rearrange and click through all images of the collection in a slider kind of fashion.

![image](https://user-images.githubusercontent.com/1121873/31024948-51647964-a506-11e7-9a98-deabfa8b872b.png)

**Comment by jonathanhudak** [comment]
🤚🏻I got this

**Comment by jonathanhudak** [comment]
@shiftsave after looking into this a bit I have a few questions regarding the UI:

Would the thumbnails below the main image overflow horizontally only? If so we'll need carousel-like behavior for that row. This would make drag and drop behavior awkward as not all of the images would be visible together — and the drag/touch behavior would conflict with any drag behavior of the carousel. Additionally we need UI for navigating the carousel (next/prev buttons, pagination dots) etc. I've taken a quick initial stab using [Nuka Carousel](https://github.com/FormidableLabs/nuka-carousel) which demos the added UI. 
<img width="1125" alt="screen shot 2017-10-21 at 8 46 38 am" src="https://user-images.githubusercontent.com/1223821/31853406-9c8d569e-b63c-11e7-86a5-ff4127ebee4b.png">

Alternatively, we could display the images below in a normal even grid - but then it would grow too tall and be awkward to navigate.

Perhaps we should add controls to toggle different viewing modes? A re-order control could alter the UI to just display the images in a re-orderable grid.

**Comment by shiftsave** [comment]
@hudakdidit I think this definitely needs more thought, perhaps we should re-use the storyboard view like it displays currently for now and move on to the video player since this is much more important - thoughts?

**Comment by jonathanhudak** [comment]
@shiftsave hey this sounds good. I'll shift to the video player.

**Comment by shiftsave** [comment]
@hudakdidit I think that for time's sake we should re-use the storyboard component for this view and just style it differently on the customer side. So the way the gallery is created is the same Grid component we use for both storyboards and moodboard and can either slap it into a carousel on client mode or even just scrolling images for the time being.
