### ISSUE TITLE
Update to React Router 4

### ISSUE THREAD

**Issue by shiftsave** [shiftsave/anni-platform#63]
<img width="840" alt="screen shot 2018-05-02 at 8 59 08 pm" src="https://user-images.githubusercontent.com/1121873/39557235-b6cda912-4e4b-11e8-8b12-3b417a29ca19.png">

Issues are stacking up with RR2.x I tried to move us to RR4 but started hitting a bunch of walls as I am not super familiar with redux..

**Comment by jonathanhudak** [comment]
Dropping in favor of reach router https://github.com/reach/router

**Comment by shiftsave** [comment]
I love reach router. Been playing around with it and pose from posemotion
for transitions on my mezcal website I'll send you a peek
