### ISSUE TITLE
Error while uploading files

### ISSUE THREAD

**Issue by shiftsave** [shiftsave/anni-platform#8]
@hudakdidit I tried running your latest commit but get this error when I try to upload files

```[HMR] Waiting for update signal from WDS...
adapters.js:76 Uncaught (in promise) TypeError: Cannot read property 'filesListFolder' of null(…)
adapters.js:106 Uncaught (in promise) TypeError: Cannot read property 'filesListFolder' of null(…)
client:23 [WDS] Hot Module Replacement enabled.
adapters.js:76 Uncaught (in promise) TypeError: Cannot read property 'filesListFolder' of null(…)
adapters.js:106 Uncaught (in promise) TypeError: Cannot read property 'filesListFolder' of null(…)
adapters.js:72 Uncaught (in promise) TypeError: Cannot read property 'filesUpload' of null(…)```

**Comment by shiftsave** [comment]
same for creating new projects:
```adapters.js:84 Uncaught TypeError: Cannot read property 'filesCreateFolder' of null(…)```

**Comment by jonathanhudak** [comment]
Do you have the .env.json setup?

**Comment by jonathanhudak** [comment]
@shiftsave hmm. I can't repro the issue. If you're getting that error `client` is  null in `adapters.js`. Something seems to be wrong with your authentication with dropbox. Could you click the '(...)' in the error in each of those errors in the console and send the stack trace?

You may need to logout and re-login to dropbox. If that doesn't work, try deleting your session storage for localhost:3000, refresh, and then log back in.

**Comment by shiftsave** [comment]
Oh weird, I just did that and worked! awesome, thanks yo!

**Comment by shiftsave** [comment]
@hudakdidit the error is still there. I ended up deleting my local repo and cloning again with a new db app name, and can't do anything. If I try to create a new app it gives me an error (see below) and if I refresh the page the project is actually there BUT can't access it's content.

<img width="1281" alt="screen shot 2016-12-12 at 4 41 15 pm" src="https://cloud.githubusercontent.com/assets/1121873/21122886/dac62214-c089-11e6-960b-3cc93392080c.png">
<img width="798" alt="screen shot 2016-12-12 at 4 36 38 pm" src="https://cloud.githubusercontent.com/assets/1121873/21122888/dae1cafa-c089-11e6-8aa8-c40c942e8f54.png">

**Comment by jonathanhudak** [comment]
Should have tested that sorry, should be fixed with the latest commit

**Comment by shiftsave** [comment]
There was a typo in your last commit in `validateAuthentication` I pushed a small commit to fix it and now is working!

**Comment by jonathanhudak** [comment]
I did it from my phone 😛 Cool

**Comment by shiftsave** [comment]
hahahaha
